### PR TITLE
Shards

### PR DESCRIPTION
**Pull request by rhysnewell**
Hi Ben,
Here is the work on shards branch as of yesterday. Still have to go through some of the things you mentioned, but most of it is good and working. I am wondering whether the reads do need to be renamed/numbered, as it seems functional without it. Maybe I'm misunderstanding why the numbering needs to be done in the first place.

rhys

### CODE REVIEW

**Comment by wwood** [comment]
Nice. Don't worry about the read numbering, it was just an optimisation idea so that we could not do the samtools sort -n. Let me know when you've finished this all off and I'll take a look at it then.
thanks again.

**Comment by wwood** [comment]
Thanks - so are we ready to try merging?

**Comment by rhysnewell** [comment]
I think so!

**Comment by wwood** [comment]
Nice, alrighty I'll give it a go.

**Comment by wwood** [comment]
Hey I'm thinking things got a little crazy here because maybe I did a rebase or something. Does it make sense to do another pull request?
ta

**Comment by rhysnewell** [comment]
Woah, I didn't realise this would show up here? I was just resolving my local and repo branch to be up to day with what you've done. Maybe best to close this pull request and start up another?

Has my pull and push screwed up your repo?

**Comment by wwood** [comment]
No no nothing ruined, don't worry. I think you just need to start a new branch. I'll close this now.

**Pull request closed without merging**
