### PR TITLE
add citation

### PR DESCRIPTION
**Pull request by AroneyS**

### CODE REVIEW

**Comment by AroneyS** [comment]
Master is still the default branch btw

**Comment by wwood** [comment]
Hey can you add Nissen J., Carmago A., please?

**Comment by wwood** [comment]
>Master is still the default branch btw

On GitHub it isn't. Maybe I misunderstand?

**Comment by AroneyS** [comment]
Oh weird. It just defaulted to master for this pull request. Maybe its due to my fork's settings

**Comment by AroneyS** [comment]
Like that?

**Comment by AroneyS** [comment]
Do you have their orcids? Or google scholar links? Or a paper?

**Pull request merged**
