### PR TITLE
Updated to rust_htslib 0.29 and Updated Dereplicate function

### PR DESCRIPTION
**Pull request by rhysnewell**
Hey Ben,

Just handled all the u64 shenanigans for rust_htslib 0.29 and also updated dereplicate function to use the correct struct fields.

The tests seemed to run fine but something odd was happening where it says it failed but all the tests passed? Might be something wrong with my environment and worth double checking on your end?

Cheers,
Rhys

### CODE REVIEW

**Comment by rhysnewell** [comment]
So the tests on travis-ci passed except for the two that made use of Galah, so I think something has to change in Galah for those to work again but everything else seems good.

Pretty sure this update will allow us to multithread the coverage calculations across multiple bams at a time, since the bam reader type now implements Send.

Rhys

**Comment by wwood** [comment]
Thanks. Let me know when you are finished work on this branch and it is ready for review.

**Comment by wwood** [comment]
Hey, I've fixed those galah errors now on master.

Is the first commit 1e892bb15d a good idea to cherry pick? Or should I wait for further efforts here?
ta

**Comment by wwood** [comment]
ie use that first commit, except update to 0.30 rather than 0.29

**Comment by rhysnewell** [comment]
Hey Ben, 
yeah probably good to go. I tried adding in some additional multithreading when looping through the bam generators but it was feeling a bit hacky so I may just leave it.

If 0.30 is out then go for it, hopefully no other fixes needed.

Rhys

**Comment by wwood** [comment]
OK, I've updated to 0.30 using your code. Thanks. I had a look at all the files changed here, and it seems you've almost no changes beyond u32 -> u64. Not sure what makes you think hacky things have gone on here?

Multithreaded reading would be useful but would take some though as to how to share threads between mapping/samtools and internally within coverm. If only they were all written in rust..

I might close this now - multithreading can be another PR if you end up going down that road.
Thanks.

**Pull request closed without merging**
