### PR TITLE
adding in set_threads option

### PR DESCRIPTION
**Pull request by rhysnewell**
Just the bam reader multithreading implemented in rust htslib

### CODE REVIEW

**Comment by wwood** [comment]
Thanks Rhys.

From the documentation
https://docs.rs/rust-htslib/0.26.0/rust_htslib/bam/trait.Read.html#method.set_threads

I think it is asking for the number of extra threads, not the total number of threads. So I think some kind of logic like
```
if n_threads > 1 {
  set_threads(n_threads-1)
}
```
is needed, yeh?

**Comment by wwood** [comment]
Hey, not sure whether it is best to set threads during the reading methods, or during the bam generation code, but since you've done this then we can probably merge this. Can you just undelete that test data file and check please? Also, does this show up in benchmarking? I've deployed this to /gnu/store/s7yhr6083bvbbb1v0bx6sldq7mycphsg-coverm-dev-0.0.0.dev/bin/coverm on the servers.

Thanks again.

**Comment by rhysnewell** [comment]
Yeah, I’ve just moved it into the bam generator. Makes more sense for future usages of set_threads to keep thread counts consistent and stuff. And yep, I’ve no idea how that file got deleted.

Rhys



________________________________

**Comment by wwood** [comment]
Hi Rhys, I've incorporated your changes in as 3ccf8ed6895b4641b383ffcae2bd5a775f35ec84 and pushed to master. Thanks.

**Pull request closed without merging**
